apiVersion: v1
kind: Service
metadata:
  labels:
    name: juice-deployment
  name: juice-svc-5
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30054
  selector:
    name: juice-pod-5
  type: NodePort
