apiVersion: apps/v1
kind: Deployment
metadata:
    name: juice-deploy-1
    labels:
        name: juice-deployment-1
    namespace: prod
spec:
    replicas: 1
    selector:
        matchLabels:
            name: juice-pod-1
    template:
        metadata:
            name: juice-pod-1
            labels:
                name: juice-pod-1
        spec:
            containers:
             - name: juice
               image: bkimminich/juice-shop
               env:
               - name: NODE_ENV
                 value: unsafe
               ports:
                - containerPort: 3000
             - command:
                - /wrapper.sh
                - -m=waas-controller-service
                - -n=k8swaf.svc
                - -s=waas-rate-limiter-service
                - -a=k8swaf.svc
                - -p=prod/juice-profile
                - -t=juice
                - -e
                - --statsd-port=8125
                - -c=0.0.0.0:9000:Juice-Policy:127.0.0.1:3000
#                - -l=$HOSTNAME_access.log
#                - -f=$HOSTNAME_security.log
                - --controller-tls=true
                - --controller-tls-client-auth=true
                - --controller-tls-client-crt-file=/etc/tls/tls.crt
                - --controller-tls-client-key-file=/etc/tls/tls.key
                - --controller-tls-ca-file=/etc/tls/ca/ca.crt
                - --rl-tls=true
                - --rl-tls-client-auth=true
                - --rl-tls-client-crt-file=/etc/rate-limiter/tls/tls.crt
                - --rl-tls-client-key-file=/etc/rate-limiter/tls/tls.key
                - --rl-tls-ca-file=/etc/rate-limiter/ca/ca.crt
               env:
               - name: ENFORCER_OPT_L
                 value: info
               - name: ENFORCER_OPT_BASE_ID
                 value: "321"
               image: repo:5000/waas-bootstrap1.14.0
               imagePullPolicy: IfNotPresent
               livenessProbe:
#                   exec:
#                     command:
#                     - /health_check.sh
#                   failureThreshold: 3
#                   periodSeconds: 10
#                   successThreshold: 1
#                   timeoutSeconds: 1
               name: enforcer
               ports:
                - containerPort: 19010
                  name: stats
                  protocol: TCP
 #              readinessProbe:
 #                 exec:
 #                   command:
 #                   - /health_check.sh
 #                 failureThreshold: 3
 #                 periodSeconds: 10
 #                 successThreshold: 1
 #                 timeoutSeconds: 1
               resources: {}
               securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - all
                  readOnlyRootFilesystem: true
                  runAsGroup: 65534
                  runAsUser: 65534
               terminationMessagePath: /dev/termination-log
               terminationMessagePolicy: File
               volumeMounts:
                - mountPath: /logs
                  name: logs-volume
                - mountPath: /etc/waas-config
                  name: waas-config-volume
                - mountPath: /etc/tls
                  name: controller-client-volume
                - mountPath: /etc/tls/ca
                  name: controller-ca-volume
                - mountPath: /etc/rate-limiter/tls
                  name: rate-limiter-client-volume
                - mountPath: /etc/rate-limiter/ca
                  name: rate-limiter-ca-volume
                - mountPath: /opt/waas_response_templates/
                  name: enrich-volume
             - env:
               - name: PROCESS_TO_SIGNAL
                 value: waas_enforcer
               - name: ROTATE_SIZE
                 value: 100M
               - name: ROTATE_NUM
                 value: "3"
               - name: ROTATE_EVERY
                 value: "60"
               image: repo:5000/waas-logrotate1.14.0
               imagePullPolicy: IfNotPresent
               name: logrotate
               resources: {}
               securityContext:
                 allowPrivilegeEscalation: false
                 capabilities:
                   drop:
                   - all
                 readOnlyRootFilesystem: true
                 runAsGroup: 65534
                 runAsUser: 65534
               terminationMessagePath: /dev/termination-log
               terminationMessagePolicy: File
               volumeMounts:
               - mountPath: /logs
                 name: logs-volume
             - env:
               - name: FB_LS_HOST
                 value: waas-logstash-service.k8swaf.svc
               - name: FB_PREFIX
                 value: juice-pod-1.prod
               - name: FB_LOG_LEVEL
                 value: info
               - name: FB_FLUSH
                 value: "1"
               - name: FB_HTTP_PORT
                 value: "2020"
               - name: FB_LOGS_PATH
                 value: /logs
               - name: FB_LS_PORT
                 value: "2020"
               - name: FB_MEM_BUF_LIMIT
                 value: 100m
               - name: FB_HTTP_LISTEN
                 value: 0.0.0.0
               - name: FB_STATSD_PORT
                 value: "8125"
               - name: FB_STATSD_LISTEN
                 value: 127.0.0.1
               - name: FB_TLS
                 value: "On"
               - name: FB_TLS_MTLS
                 value: "On"
               - name: FB_TLS_VERIFY
                 value: "On"
               - name: FB_TLS_CA_FILE
                 value: /etc/securebeat/ca/ca.crt
               - name: FB_TLS_CRT_FILE
                 value: /etc/securebeat/client/tls.crt
               - name: FB_TLS_KEY_FILE
                 value: /etc/securebeat/client/tls.key
               image: repo:5000/waas-fluentbit1.14.0
               imagePullPolicy: IfNotPresent
               name: fluentbit
               resources: {}
               securityContext:
                 allowPrivilegeEscalation: false
                 capabilities:
                   drop:
                   - all
                 readOnlyRootFilesystem: true
                 runAsGroup: 65534
                 runAsUser: 65534
               terminationMessagePath: /dev/termination-log
               terminationMessagePolicy: File
               volumeMounts:
               - mountPath: /etc/securebeat/client
                 name: securebeat-client-volume
               - mountPath: /etc/securebeat/ca
                 name: waas-ca-volume
               - mountPath: /logs
                 name: logs-volume
            initContainers:
            - args:
              - kopy
              - /src/enforcer/waas_aw_db
              - /enrich
              image: repo:5000/waas-enrich1.14.0
              imagePullPolicy: IfNotPresent
              name: init-enrich
              resources: {}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - all
                readOnlyRootFilesystem: true
                runAsGroup: 65534
                runAsUser: 65534
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /enrich
                name: enrich-volume            
            volumes:
              - name: waas-ca-volume
                configMap:
                  defaultMode: 420
                  name: waas-ca-config
              - name: rate-limiter-ca-volume
                configMap:
                  defaultMode: 420
                  name: waas-ca-config
              - name: controller-ca-volume
                configMap:
                  defaultMode: 420
                  name: waas-ca-config
              - name: securebeat-client-volume
                secret:
                   defaultMode: 420
                   secretName: waas-securebeat-client-secret
              - name: controller-client-volume
                secret:
                   defaultMode: 420
                   secretName: waas-securebeat-client-secret
              - name: rate-limiter-client-volume
                secret:
                   defaultMode: 420
                   secretName: waas-securebeat-client-secret
              - name: logs-volume
                emptyDir: {}
              - name: waas-config-volume
                emptyDir: {}
              - name: enrich-volume
                emptyDir: {}
            