apiVersion: apps/v1
kind: Deployment
metadata:
    name: juice-deploy-5
    labels:
        name: juice-deployment-5
    namespace: prod
spec:
    replicas: 1
    selector:
        matchLabels:
            name: juice-pod-5
    template:
        metadata:
            name: juice-pod-5
            labels:
                name: juice-pod-5
        spec:
            containers:
             - name: juice
               image: bkimminich/juice-shop
               env:
               - name: NODE_ENV
                 value: unsafe
               ports:
                - containerPort: 3000
