apiVersion: v1
kind: Service
metadata:
  labels:
    name: juice-deployment
  name: juice-svc-1
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30050
  selector:
    name: juice-pod-1
  type: NodePort
