apiVersion: v1
kind: Service
metadata:
  labels:
    name: juice-deployment
  name: juice-svc-7
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30057
  selector:
    name: juice-pod-7
  type: NodePort
