apiVersion: v1
kind: Service
metadata:
  labels:
    name: juice-deployment
  name: juice-svc-3
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30052
  selector:
    name: juice-pod-3
  type: NodePort
