apiVersion: v1
kind: Service
metadata:
  labels:
    name: juice-deployment
  name: juice-svc-4
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30053
  selector:
    name: juice-pod-4
  type: NodePort
